package hibernate_pojo;
// Generated 2019/3/21 ¤U¤È 02:57:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Merchandise generated by hbm2java
 */
@Entity
@Table(name="merchandise"
    ,catalog="test"
    , uniqueConstraints = @UniqueConstraint(columnNames="merchandise_name") 
)
public class Merchandise  implements java.io.Serializable {


     private Integer merchandiseId;
     private String merchandiseName;
     private String merchandiseCategory;
     private String merchandiseDescription;
     private boolean saleable;
     private Integer price;
     private Integer bought;
     private Set orders = new HashSet(0);

    public Merchandise() {
    }

	
    public Merchandise(String merchandiseName, String merchandiseCategory, boolean saleable) {
        this.merchandiseName = merchandiseName;
        this.merchandiseCategory = merchandiseCategory;
        this.saleable = saleable;
    }
    public Merchandise(String merchandiseName, String merchandiseCategory, String merchandiseDescription, boolean saleable, Integer price, Integer bought, Set orders) {
       this.merchandiseName = merchandiseName;
       this.merchandiseCategory = merchandiseCategory;
       this.merchandiseDescription = merchandiseDescription;
       this.saleable = saleable;
       this.price = price;
       this.bought = bought;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="merchandise_id", unique=true, nullable=false)
    public Integer getMerchandiseId() {
        return this.merchandiseId;
    }
    
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    
    @Column(name="merchandise_name", unique=true, nullable=false, length=20)
    public String getMerchandiseName() {
        return this.merchandiseName;
    }
    
    public void setMerchandiseName(String merchandiseName) {
        this.merchandiseName = merchandiseName;
    }

    
    @Column(name="merchandise_category", nullable=false, length=20)
    public String getMerchandiseCategory() {
        return this.merchandiseCategory;
    }
    
    public void setMerchandiseCategory(String merchandiseCategory) {
        this.merchandiseCategory = merchandiseCategory;
    }

    
    @Column(name="merchandise_description", length=30)
    public String getMerchandiseDescription() {
        return this.merchandiseDescription;
    }
    
    public void setMerchandiseDescription(String merchandiseDescription) {
        this.merchandiseDescription = merchandiseDescription;
    }

    
    @Column(name="saleable", nullable=false)
    public boolean isSaleable() {
        return this.saleable;
    }
    
    public void setSaleable(boolean saleable) {
        this.saleable = saleable;
    }

    
    @Column(name="price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

    
    @Column(name="bought")
    public Integer getBought() {
        return this.bought;
    }
    
    public void setBought(Integer bought) {
        this.bought = bought;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="merchandise")
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


