package hibernate_pojo;
// Generated 2019/3/21 ¤U¤È 02:57:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="test"
)
public class Order  implements java.io.Serializable {


     private Integer orderIdKey;
     private Member member;
     private Merchandise merchandise;
     private Integer orderId;
     private Date time;
     private Integer consumptionAmount;
     private Integer quantity;

    public Order() {
    }

	
    public Order(Member member, Merchandise merchandise) {
        this.member = member;
        this.merchandise = merchandise;
    }
    public Order(Member member, Merchandise merchandise, Integer orderId, Date time, Integer consumptionAmount, Integer quantity) {
       this.member = member;
       this.merchandise = merchandise;
       this.orderId = orderId;
       this.time = time;
       this.consumptionAmount = consumptionAmount;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id_key", unique=true, nullable=false)
    public Integer getOrderIdKey() {
        return this.orderIdKey;
    }
    
    public void setOrderIdKey(Integer orderIdKey) {
        this.orderIdKey = orderIdKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_id", nullable=false)
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="merchandise_id", nullable=false)
    public Merchandise getMerchandise() {
        return this.merchandise;
    }
    
    public void setMerchandise(Merchandise merchandise) {
        this.merchandise = merchandise;
    }

    
    @Column(name="order_id")
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time", length=19)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    
    @Column(name="consumption_amount")
    public Integer getConsumptionAmount() {
        return this.consumptionAmount;
    }
    
    public void setConsumptionAmount(Integer consumptionAmount) {
        this.consumptionAmount = consumptionAmount;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


